/*
 * Generated by Airoha Easy PinMux Tool Version 2.7.4 for AB1565. Copyright Airoha Inc. (C) 2015.
 * 2023-07-05 16:41:13:0185
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
